--CREACION DE BASE DE DATOS Y EL USUARIO

CREATE TABLESPACE PARQUEO_DAT
    DATAFILE 'C:\Users\Josue\Documents\Sistema Llobet\PARQUEO_DAT.DBF'
    SIZE 100M ONLINE;

CREATE TEMPORARY TABLESPACE PARQUEO_TEMP
    TEMPFILE 'C:\Users\Josue\Documents\Sistema Llobet\PARQUEO_TEMP.DBF'
    SIZE 3M AUTOEXTEND ON;
    
CREATE USER PARQUEO IDENTIFIED BY 010595
    DEFAULT TABLESPACE PARQUEO_DAT
    TEMPORARY TABLESPACE PARQUEO_TEMP;
    
--ACCESOS

GRANT RESOURCE TO PARQUEO;
GRANT CONNECT TO PARQUEO;
GRANT ALL PRIVILEGES TO PARQUEO;

CREATE TABLE PARQUEO.PARAMETROS(
    ID_PARAMETRO        VARCHAR2(10) NOT NULL PRIMARY KEY,
    NOMBRE_PARQUEO      VARCHAR2(100),
    MENSAJE_OPCIONAL    VARCHAR2(100));
    
CREATE TABLE PARQUEO.EMPRESA(
    ID_EMPRESA      NUMBER NOT NULL PRIMARY KEY,
    NOMBRE_EMPRESA  VARCHAR2(45),
    CEDULA_JURIDICA VARCHAR2(45),
    TELEFONO        VARCHAR2(12));
    
CREATE TABLE PARQUEO.AUTORIZADOS(
    ID_AUTORIZADO       NUMBER NOT NULL PRIMARY KEY,
    NOMB_AUTORIZADO     VARCHAR2(45),
    APELL_AUTORIZADO    VARCHAR2(45),
    TELEFONO            VARCHAR2(12),
    TIPO_CLIENTE        NUMBER,
    ESTADO              NUMBER);
        
CREATE TABLE PARQUEO.PLACAS(
    ID_PLACA        VARCHAR2(7) NOT NULL PRIMARY KEY,
    ID_AUTORIZADO   NUMBER,
    CUOTA           NUMBER,
    MED_TRANSPORTE  NUMBER,
    ESTADO          NUMBER);
        
CREATE TABLE PARQUEO.TIPOS_CLIENTES(
    ID_CLIENTE   NUMBER NOT NULL PRIMARY KEY,
    TIPO_CLIENTE VARCHAR(10));
    
CREATE TABLE PARQUEO.TIPOS_MEDIOS_TRANSPORTE(
    ID_MEDIO    NUMBER NOT NULL PRIMARY KEY,
    TIPO_MEDIO  VARCHAR2(50),
    COBRO       NUMBER);
    
CREATE TABLE PARQUEO.LUGARES(
    ID_LUGAR            VARCHAR2(3) NOT NULL PRIMARY KEY,
    TIPO_MEDIO_LUGAR    NUMBER NOT NULL,
    ESTADO              NUMBER);
    
CREATE TABLE PARQUEO.USUARIOS(
    ID_USUARIO      NUMBER NOT NULL PRIMARY KEY,
    NOMBRE_USUARIO  VARCHAR2(45) UNIQUE,
    CLAVE           VARCHAR2(45),
    ESTADO          NUMBER DEFAULT 1);
    
CREATE TABLE PARQUEO.REPORTES(
    ID_REPORTE  NUMBER NOT NULL PRIMARY KEY,
    CAJA        NUMBER);
    
CREATE TABLE PARQUEO.MEDIOS_ACTUALES(
    ID_ACTUAL       NUMBER NOT NULL PRIMARY KEY,
    NUMERO_PLACA    VARCHAR2(7) NOT NULL,
    ENTRADA         NUMBER NOT NULL,
    FECHA_HORA_ENT  VARCHAR2(30),
    TIPO_TRANSPORTE NUMBER,
    TIPO_CLIENTE    NUMBER,
    LUGAR           VARCHAR2(3));
        
CREATE TABLE PARQUEO.CAJAS(
    ID_CAJA         NUMBER NOT NULL PRIMARY KEY,
    FECHA_HORA_ABRE VARCHAR2(30),
    FECHA_HORA_CIER VARCHAR2(30),
    MONTO_TOTAL     NUMBER,
    MEDIOS_ACT      NUMBER,
    USUARIO         NUMBER);
        
CREATE TABLE PARQUEO.TIQUETE_ENTRADA(
    ID_ENTRADA      NUMBER NOT NULL PRIMARY KEY,
    FECHA_HORA      VARCHAR2(30),
    NUM_PLACA       VARCHAR2(7),
    LUGAR           VARCHAR2(3),
    TARIFA          NUMBER);
        
CREATE TABLE PARQUEO.TIQUETE_SALIDA(
    ID_SALIDA       NUMBER NOT NULL PRIMARY KEY,
    ID_ENTRADA      NUMBER,
    NUM_PLACA       VARCHAR2(7),
    FECHA_HORA_ENT  VARCHAR2(30),
    FECHA_HORA_SAL  VARCHAR2(30),
    TIEMPO_EFECTIVO VARCHAR2(50),
    MONTO_COBRADO   NUMBER,
    LUGAR           VARCHAR(3),
    TARIFA          NUMBER);
    
--LAVES FORANEAS
        
ALTER TABLE PARQUEO.PLACAS ADD CONSTRAINT FK_ID_AUTORIZADO FOREIGN KEY (ID_AUTORIZADO) REFERENCES PARQUEO.AUTORIZADOS(ID_AUTORIZADO);

ALTER TABLE PARQUEO.AUTORIZADOS ADD CONSTRAINT FK_TIPO_CLIENTE FOREIGN KEY (TIPO_CLIENTE) REFERENCES PARQUEO.TIPOS_CLIENTES(ID_CLIENTE);
    
ALTER TABLE PARQUEO.LUGARES ADD CONSTRAINT FK_MED_TRANSPORTE FOREIGN KEY (TIPO_MEDIO_LUGAR) REFERENCES PARQUEO.TIPOS_MEDIOS_TRANSPORTE(ID_MEDIO);

ALTER TABLE PARQUEO.MEDIOS_ACTUALES ADD CONSTRAINT FK_ID_ENTRADA FOREIGN KEY (ENTRADA) REFERENCES PARQUEO.TIQUETE_ENTRADA(ID_ENTRADA);
ALTER TABLE PARQUEO.MEDIOS_ACTUALES ADD CONSTRAINT FK_TIPO_TRANSPORTE FOREIGN KEY (TIPO_TRANSPORTE) REFERENCES PARQUEO.TIPOS_MEDIOS_TRANSPORTE(ID_MEDIO);
ALTER TABLE PARQUEO.MEDIOS_ACTUALES ADD CONSTRAINT FK_TIPO_CLIENTE FOREIGN KEY (TIPO_CLIENTE) REFERENCES PARQUEO.TIPOS_CLIENTES(ID_CLIENTE);
ALTER TABLE PARQUEO.MEDIOS_ACTUALES ADD CONSTRAINT FK_LUGAR FOREIGN KEY (LUGAR) REFERENCES PARQUEO.LUGARES(ID_LUGAR);

ALTER TABLE PARQUEO.CAJAS ADD CONSTRAINT FK_USUARIO FOREIGN KEY (USUARIO) REFERENCES PARQUEO.USUARIOS(ID_USUARIO);

ALTER TABLE PARQUEO.TIQUETE_ENTRADA ADD CONSTRAINT FK_CAMPO_LUGAR FOREIGN KEY (LUGAR) REFERENCES PARQUEO.LUGARES(ID_LUGAR);

ALTER TABLE PARQUEO.TIQUETE_SALIDA ADD CONSTRAINT FK_ENTRADA FOREIGN KEY (ID_ENTRADA) REFERENCES PARQUEO.TIQUETE_ENTRADA(ID_ENTRADA);
ALTER TABLE PARQUEO.TIQUETE_SALIDA ADD CONSTRAINT FK_CAMP_LUGAR FOREIGN KEY (LUGAR) REFERENCES PARQUEO.LUGARES(ID_LUGAR);

--TRIGGERS Y SEQUENCIAS

CREATE SEQUENCE SEQ_AUT
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRIG_AUTORIZADOS
BEFORE INSERT ON AUTORIZADOS
FOR EACH ROW
BEGIN SELECT SEQ_AUT.NEXTVAL INTO :NEW.ID_AUTORIZADO FROM DUAL;
END;

CREATE SEQUENCE SEQ_ENTRADA
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_SALIDA
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRIG_SALIDA
BEFORE INSERT ON TIQUETE_SALIDA
FOR EACH ROW
BEGIN SELECT SEQ_SALIDA.NEXTVAL INTO :NEW.ID_SALIDA FROM DUAL;
END;

CREATE SEQUENCE SEQ_MED_ACT
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRIG_MED_ACT
BEFORE INSERT ON MEDIOS_ACTUALES
FOR EACH ROW
BEGIN SELECT SEQ_MED_ACT.NEXTVAL INTO :NEW.ID_ACTUAL FROM DUAL;
END;

CREATE SEQUENCE SEQ_USUARIOS
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRIG_USUARIOS
BEFORE INSERT ON USUARIOS
FOR EACH ROW
BEGIN SELECT SEQ_USUARIOS.NEXTVAL INTO :NEW.ID_USUARIO FROM DUAL;
END;

--INSERCIONES NECESARIAS

INSERT INTO PARQUEO.PARAMETROS (ID_PARAMETRO, NOMBRE_PARQUEO, MENSAJE_OPCIONAL) VALUES ('1', 'La Rambla', 'Nuevo sistema de parqueo');

INSERT INTO PARQUEO.TIPOS_CLIENTES (ID_CLIENTE, TIPO_CLIENTE) VALUES (1, 'GENERICO');
INSERT INTO PARQUEO.TIPOS_CLIENTES (ID_CLIENTE, TIPO_CLIENTE) VALUES (2, 'AUTORIZADO');

INSERT INTO PARQUEO.AUTORIZADOS (NOMB_AUTORIZADO, TIPO_CLIENTE, ESTADO) VALUES ('GENERICO', 1, 1);

INSERT INTO PARQUEO.LUGARES(ID_LUGAR, ESTADO) VALUES('M1', 1);
INSERT INTO PARQUEO.LUGARES(ID_LUGAR, ESTADO) VALUES('M2', 1);
INSERT INTO PARQUEO.LUGARES(ID_LUGAR, ESTADO) VALUES('C1', 1);
INSERT INTO PARQUEO.LUGARES(ID_LUGAR, ESTADO) VALUES('C2', 1);
INSERT INTO PARQUEO.LUGARES(ID_LUGAR, ESTADO) VALUES('C3', 1);
INSERT INTO PARQUEO.LUGARES(ID_LUGAR, ESTADO) VALUES('C4', 1);
INSERT INTO PARQUEO.LUGARES(ID_LUGAR, ESTADO) VALUES('C5', 1);
INSERT INTO PARQUEO.LUGARES(ID_LUGAR, ESTADO) VALUES('C6', 1);
INSERT INTO PARQUEO.LUGARES(ID_LUGAR, ESTADO) VALUES('C7', 1);
INSERT INTO PARQUEO.LUGARES(ID_LUGAR, ESTADO) VALUES('C8', 1);
INSERT INTO PARQUEO.LUGARES(ID_LUGAR, ESTADO) VALUES('C9', 1);
INSERT INTO PARQUEO.LUGARES(ID_LUGAR, ESTADO) VALUES('C10', 1);

INSERT INTO PARQUEO.TIPOS_MEDIOS_TRANSPORTE(ID_MEDIO, TIPO_MEDIO, COBRO) VALUES(1, 'CARRO', 900);
INSERT INTO PARQUEO.TIPOS_MEDIOS_TRANSPORTE(ID_MEDIO, TIPO_MEDIO, COBRO) VALUES(2, 'MOTO', 800);

