ALTER TABLE PARQUEO.PARAMETROS ADD USUARIO_ON NUMBER;

ALTER TABLE PARQUEO.USUARIOS ADD TIPO_USUARIO NUMBER;

ALTER TABLE PARQUEO.PARAMETROS ADD IMAGEN VARCHAR2(200);

--EN ESTA ACTUALIZACION PONEN LA DIRECCION DONDE TIENEN LA IMAGEN GUARDADA
UPDATE PARQUEO.PARAMETROS SET IMAGEN = 'C:\Users\Josue\Documents\Sistema Llobet\Llobet_Logo.JPG';

CREATE OR REPLACE PROCEDURE PARQUEO.LOGEAR (USUARIO_ID NUMBER) IS
BEGIN
    UPDATE PARQUEO.PARAMETROS SET USUARIO_ON = USUARIO_ID;
    COMMIT;
END;

CREATE OR REPLACE PROCEDURE ACTUALIZAR_AUTORIZADOS (P_ID_AUTORIZADO NUMBER, P_NOMB_AUTORIZADO VARCHAR2, P_APELL_AUTORIZADO VARCHAR2, P_TELEFONO VARCHAR2, P_TIPO_CLIENTE NUMBER, P_ESTADO NUMBER) IS
BEGIN
    UPDATE PARQUEO.AUTORIZADOS SET NOMB_AUTORIZADO = P_NOMB_AUTORIZADO, APELL_AUTORIZADO = P_APELL_AUTORIZADO, 
    TELEFONO = P_TELEFONO, TIPO_CLIENTE = P_TIPO_CLIENTE, ESTADO = P_ESTADO WHERE ID_AUTORIZADO = P_ID_AUTORIZADO;
    COMMIT;
END;

CREATE OR REPLACE PROCEDURE ACTUALIZAR_USUARIOS (P_ID_USUARIO NUMBER, P_NOMBRE_USUARIO VARCHAR2, P_CLAVE VARCHAR2, P_TIPO_USUARIO NUMBER, P_ESTADO NUMBER) IS
BEGIN    
    UPDATE PARQUEO.USUARIOS SET NOMBRE_USUARIO = P_NOMBRE_USUARIO, CLAVE = P_CLAVE, 
    TIPO_USUARIO = P_TIPO_USUARIO, ESTADO = P_ESTADO WHERE ID_USUARIO = P_ID_USUARIO;
    COMMIT;
END;

CREATE OR REPLACE PROCEDURE PARQUEO.ACTUALIZAR_LUGARES (P_ID_LUGAR VARCHAR2, P_TIPO_MEDIO_LUGAR NUMBER, P_ESTADO NUMBER) IS
BEGIN    
    UPDATE PARQUEO.LUGARES SET TIPO_MEDIO_LUGAR = P_TIPO_MEDIO_LUGAR, 
    ESTADO = P_ESTADO WHERE ID_LUGAR = P_ID_LUGAR;
    COMMIT;
END;

CREATE OR REPLACE PROCEDURE PARQUEO.ACTUALIZAR_TIPOS_VEHICULOS (P_ID_MEDIO NUMBER, P_TIPO_MEDIO VARCHAR2, P_COBRO NUMBER) IS
BEGIN    
    UPDATE PARQUEO.TIPOS_MEDIOS_TRANSPORTE SET TIPO_MEDIO = P_TIPO_MEDIO, 
    COBRO = P_COBRO WHERE ID_MEDIO = P_ID_MEDIO;
    COMMIT;
END;

CREATE SEQUENCE SEQ_TIPOS_MEDIOS_TRANSPORTE
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRIG_TIPOS_MEDIOS_TRANSPORTE
BEFORE INSERT ON TIPOS_MEDIOS_TRANSPORTE
FOR EACH ROW
BEGIN SELECT SEQ_TIPOS_MEDIOS_TRANSPORTE.NEXTVAL INTO :NEW.ID_MEDIO FROM DUAL;
END;

CREATE OR REPLACE PROCEDURE PARQUEO.ACTUALIZAR_PLACAS (P_ID_PLACA VARCHAR2, P_ID_AUTORIZADO NUMBER, P_CUOTA NUMBER, P_MED_TRANSPORTE NUMBER, P_ESTADO NUMBER) IS
BEGIN    
    UPDATE PARQUEO.PLACAS SET ID_AUTORIZADO = P_ID_AUTORIZADO, CUOTA = P_CUOTA, MED_TRANSPORTE = P_MED_TRANSPORTE, ESTADO = P_ESTADO
    WHERE ID_PLACA = P_ID_PLACA;
    COMMIT;
END;