ALTER TABLE PARQUEO.PARAMETROS DROP COLUMN IMAGEN;

ALTER TABLE PARQUEO.PARAMETROS ADD NUM_ENTRADA NUMBER;

ALTER TABLE PARQUEO.PARAMETROS ADD NUM_PLACA NUMBER;

INSERT INTO PARQUEO.USUARIOS (NOMBRE_USUARIO, CLAVE, TIPO_USUARIO, ESTADO)
VALUES ('ADMIN', 'ADMIN', 1, 1);

ALTER TABLE PARQUEO.TIQUETE_SALIDA ADD ID_USUARIO NUMBER;

ALTER TABLE PARQUEO.TIQUETE_SALIDA ADD CONSTRAINT FK_ID_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES PARQUEO.USUARIOS(ID_USUARIO);

COMMIT;