--CREACION DE BASE DE DATOS Y EL USUARIO

CREATE TABLESPACE PARQUEO_DAT
    DATAFILE 'C:\oraclexe\app\oracle\oradata\XE\PARQUEO_DAT.DBF'
    SIZE 100M ONLINE;

CREATE TEMPORARY TABLESPACE PARQUEO_TEMP
    TEMPFILE 'C:\oraclexe\app\oracle\oradata\XE\PARQUEO_TEMP.DBF'
    SIZE 3M AUTOEXTEND ON;
    
CREATE USER PARQUEO IDENTIFIED BY 010595
    DEFAULT TABLESPACE PARQUEO_DAT
    TEMPORARY TABLESPACE PARQUEO_TEMP;
    
--ACCESOS

GRANT RESOURCE TO PARQUEO;
GRANT CONNECT TO PARQUEO;
GRANT ALL PRIVILEGES TO PARQUEO;

--TABLAS

CREATE TABLE PARQUEO.AUTORIZADOS(
    ID_AUTORIZADO   NUMBER NOT NULL PRIMARY KEY AUTOEXTEND,
    NUM_PLACA       VARCHAR2(10),
    NOMB_DUENO      VARCHAR2(45),
    APELL_DUENO     VARCHAR2(45),
    TELEFONO        VARCHAR2(12),
    CUOTA           NUMBER,
    MED_TRANSPORTE  NUMBER,
    TIPO_CLIENTE    NUMBER,
    ESTADO          NUMBER);
    
--************CORRECION, NO SE POR QUE EL AUTORIZADO TIENE NUMERO DE PLACA, SI TIENE DOS CARROS NO PUEDE TENER UNA SOLA PLACA CREO QUE PASAR A MEDIO DE TRANSPORTE


CREATE TABLE PARQUEO.TIPOSCLIENTES(
    ID_CLIENTE   NUMBER NOT NULL PRIMARY KEY,
    TIPO_CLIENTE NUMBER);

ALTER TABLE PARQUEO.AUTORIZADOS ADD CONSTRAINT FK_CLIENTE_ID FOREIGN KEY (TIPO_CLIENTE) REFERENCES PARQUEO.TIPOSCLIENTES(ID_CLIENTE);
    
CREATE TABLE PARQUEO.TIPOSMEDIOSTRANSPORTE(
    ID_MEDIO   NUMBER NOT NULL PRIMARY KEY,
    TIPO_MEDIO  VARCHAR2(50),
    COBRO       NUMBER);
    
CREATE TABLE PARQUEO.LUGARES(
    ID_LUGAR            NUMBER NOT NULL PRIMARY KEY,
    TIPO_MEDIO_LUGAR    NUMBER NOT NULL,
    ESTADO              NUMBER);

CREATE TABLE PARQUEO.USUARIOS(
    ID_USUARIO      NUMBER NOT NULL PRIMARY KEY,
    NOMBRE_USUARIO  VARCHAR2(45),
    CLAVE           VARCHAR2(45),
    ESTADO          NUMBER);

CREATE TABLE PARQUEO.REPORTES(
    ID_REPORTE  NUMBER NOT NULL PRIMARY KEY,
    CAJA        NUMBER);

CREATE TABLE PARQUEO.MEDIOSACTUALES(
    ID_ACTUAL       NUMBER NOT NULL PRIMARY KEY,
    FECHA_ENTRADA   DATE,
    HORA_ENTRADA    TIMESTAMP,
    TIPO_TRANSPORTE NUMBER,
    TIPO_CLIENTE    NUMBER,
    LUGAR           NUMBER);

CREATE TABLE PARQUEO.ESTADOS(
    ID_ESTADO   NUMBER NOT NULL PRIMARY KEY,
    TIPO_ESTADO VARCHAR2(300));
    
CREATE TABLE PARQUEO.CAJAS(
    ID_CAJA         NUMBER NOT NULL PRIMARY KEY,
    FECHA_ABRE      DATE,
    HORA_ABRE       TIMESTAMP,
    FECHA_CIERRA    DATE,
    HORA_CIERRA     TIMESTAMP,
    MONTO_TOTAL     NUMBER,
    MEDIOS_ACT      NUMBER,
    USUARIO         NUMBER);
    
CREATE TABLE PARQUEO.TIPOSUSUARIO(
    ID_USUARIO      NUMBER NOT NULL PRIMARY KEY,
    TIPO_USUARIO    NUMBER);
    
CREATE TABLE PARQUEO.TIQUETEENTRADA(
    ID_ENTRADA      NUMBER NOT NULL PRIMARY KEY,
    NOMBRE_PARQUEO  VARCHAR2(45),
    FECHA           DATE,
    HORA_ENTRA      TIMESTAMP,
    NUM_PLACA       VARCHAR2(10),
    LUGAR           NUMBER,
    MENSAJE         VARCHAR2(200),
    TARIFA          NUMBER);
    
CREATE TABLE PARQUEO.TIQUETESALIDA(
    ID_SALIDA       NUMBER NOT NULL PRIMARY KEY,
    NOMBRE_PARQUEO  VARCHAR2(45),
    CEDULA_JURIDICA VARCHAR2(45),
    NUM_PLACA       VARCHAR2(10),
    HORA_ENTRA      TIMESTAMP,
    HORA_SALIDA     TIMESTAMP,
    TIEMPO_EFECTIVO TIMESTAMP,
    MONTO_COBRADO   NUMBER,
    FECHA           DATE,
    LUGAR           NUMBER,
    MENSAJE         VARCHAR2(200),
    TARIFA          NUMBER);
    
COMMIT;

--BORRAR TODAS LAS TABLAS

DROP TABLE PARQUEO.AUTORIZADOS;
DROP TABLE PARQUEO.CAJAS;
DROP TABLE PARQUEO.ESTADOS;
DROP TABLE PARQUEO.LUGARES;
DROP TABLE PARQUEO.MEDIOSACTUALES;
DROP TABLE PARQUEO.REPORTES;
DROP TABLE PARQUEO.TIPOSCLIENTES;
DROP TABLE PARQUEO.TIPOSMEDIOSTRANSPORTE;
DROP TABLE PARQUEO.TIPOSUSUARIO;
DROP TABLE PARQUEO.TIQUETEENTRADA;
DROP TABLE PARQUEO.TIQUETESALIDA;
DROP TABLE PARQUEO.USUARIOS;

--MODIFICACIONES

ALTER TABLE PARQUEO.LUGARES ADD CONSTRAINT FK_TIPO_MEDIO_LUGAR FOREIGN KEY (TIPO_MEDIO_LUGAR) REFERENCES PARQUEO.TIPOSMEDIOSTRANSPORTE(ID_MEDIO);
ALTER TABLE PARQUEO.LUGARES ADD CONSTRAINT FK_ESTADO FOREIGN KEY (ESTADO) REFERENCES PARQUEO.ESTADOS(ID_ESTADO);
INSERT INTO PARQUEO.ESTADOS(ID_ESTADO, TIPO_ESTADO) VALUES(0, 'OCUPADO');
INSERT INTO PARQUEO.ESTADOS(ID_ESTADO, TIPO_ESTADO) VALUES(1, 'ACTIVO');
INSERT INTO PARQUEO.ESTADOS(ID_ESTADO, TIPO_ESTADO) VALUES(2, 'INACTIVO');
INSERT INTO PARQUEO.LUGARES(ID_LUGAR, ESTADO) VALUES(0, 1);
INSERT INTO PARQUEO.LUGARES(ID_LUGAR, ESTADO) VALUES(1, 0);
INSERT INTO PARQUEO.LUGARES(ID_LUGAR, ESTADO) VALUES(2, 2);
INSERT INTO PARQUEO.TIPOSMEDIOSTRANSPORTE(ID_MEDIO, TIPO_MEDIO, COBRO) VALUES(0, 'Carro', 600);
UPDATE PARQUEO.LUGARES SET ESTADO = 1 WHERE ID_LUGAR = 1;
UPDATE PARQUEO.LUGARES SET ESTADO = 0 WHERE ID_LUGAR = 1;

--CONSULTAS

TRUNCATE TABLE PARQUE.TIPOSMEDIOSTRANSPORTE;
SELECT * FROM PARQUEO.TIPOSMEDIOSTRANSPORTE;
SELECT * FROM PARQUEO.ESTADOS;
SELECT * FROM PARQUEO.AUTORIZADOS;
SELECT * FROM PARQUEO.TIQUETEENTRADA;
SELECT * FROM PARQUEO.LUGARES JOIN ESTADOS E
ON LUGARES.ESTADO = E.ID_ESTADO;
TRUNCATE TABLE PARQUEO.ESTADOS;
TRUNCATE TABLE PARQUEO.LUGARES;
SELECT E.TIPO_ESTADO FROM LUGARES JOIN ESTADOS E
ON ID_LUGAR = E.ID_ESTADO
WHERE E.ID_ESTADO = 1;

--TRIGGERS Y SEQUENCIAS

CREATE SEQUENCE SEQ_AUT
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRIG_AUTORIZADOS
BEFORE INSERT ON AUTORIZADOS
FOR EACH ROW
BEGIN SELECT SEQ_AUT.NEXTVAL INTO :NEW.ID_AUTORIZADO FROM DUAL;
END;

CREATE SEQUENCE SEQ_ENTRADA
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRIG_ENTRADAS
BEFORE INSERT ON TIQUETEENTRADA
FOR EACH ROW
BEGIN SELECT SEQ_ENTRADA.NEXTVAL INTO :NEW.ID_ENTRADA FROM DUAL;
END;
