ALTER TABLE PARQUEO.PARAMETROS MODIFY NUM_PLACA VARCHAR2(7);

ALTER TABLE PARQUEO.PARAMETROS ADD TIEMPO_GRACIA NUMBER(2);

CREATE SEQUENCE PARQUEO.SEQ_CAJAS
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER PARQUEO.TRIG_CAJAS
BEFORE INSERT ON PARQUEO.CAJAS
FOR EACH ROW
BEGIN SELECT PARQUEO.SEQ_CAJAS.NEXTVAL INTO :NEW.ID_CAJA FROM DUAL;
END;

DROP TRIGGER PARQUEO.TRIG_SALIDA;

CREATE OR REPLACE PROCEDURE PARQUEO.ACTUALIZAR_LUGARES (P_ID_LUGAR VARCHAR2, P_TIPO_MEDIO_LUGAR NUMBER, P_ESTADO NUMBER, P_ID_LUGAR_REF VARCHAR2) IS
BEGIN    
    UPDATE PARQUEO.LUGARES SET ID_LUGAR = P_ID_LUGAR, TIPO_MEDIO_LUGAR = P_TIPO_MEDIO_LUGAR, 
    ESTADO = P_ESTADO WHERE ID_LUGAR = P_ID_LUGAR_REF;
    COMMIT;
END;

ALTER TABLE PARQUEO.PARAMETROS ADD CAJA_ACTUAL NUMBER;

ALTER TABLE PARQUEO.TIQUETE_SALIDA ADD ID_CAJA NUMBER;

ALTER TABLE PARQUEO.CAJAS DROP COLUMN MEDIOS_ACT;

DROP TRIGGER PARQUEO.TRIG_CAJAS;

CREATE OR REPLACE PROCEDURE PARQUEO.LOGEAR (USUARIO_ID NUMBER, CAJA_ACT NUMBER) IS
BEGIN
    UPDATE PARQUEO.PARAMETROS SET USUARIO_ON = USUARIO_ID;
    UPDATE PARQUEO.PARAMETROS SET CAJA_ACTUAL = CAJA_ACT;
    COMMIT;
END;

ALTER TABLE PARQUEO.PARAMETROS DROP COLUMN NOMBRE_PARQUEO;

INSERT INTO PARQUEO.EMPRESA(ID_EMPRESA, NOMBRE_EMPRESA, CEDULA_JURIDICA, TELEFONO) VALUES (1, '', '', '');

ALTER TABLE PARQUEO.PARAMETROS ADD IMPUESTO FLOAT;

ALTER TABLE PARQUEO.PARAMETROS ADD MENSAJE_HORARIO VARCHAR2(100);
UPDATE PARQUEO.PARAMETROS SET MENSAJE_HORARIO = 'LUNES A VIERNES 8 AM-7PM SABADOS Y DOMINGOS 8AM-5PM';

COMMIT;