ALTER TABLE PARQUEO.PARAMETROS MODIFY NUM_PLACA VARCHAR2(7);

ALTER TABLE PARQUEO.PARAMETROS ADD TIEMPO_GRACIA NUMBER(2);

CREATE SEQUENCE PARQUEO.SEQ_CAJAS
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER PARQUEO.TRIG_CAJAS
BEFORE INSERT ON PARQUEO.CAJAS
FOR EACH ROW
BEGIN SELECT PARQUEO.SEQ_CAJAS.NEXTVAL INTO :NEW.ID_CAJA FROM DUAL;
END;

DROP TRIGGER PARQUEO.TRIG_SALIDA;

CREATE OR REPLACE PROCEDURE PARQUEO.ACTUALIZAR_LUGARES (P_ID_LUGAR VARCHAR2, P_TIPO_MEDIO_LUGAR NUMBER, P_ESTADO NUMBER, P_ID_LUGAR_REF VARCHAR2) IS
BEGIN    
    UPDATE PARQUEO.LUGARES SET ID_LUGAR = P_ID_LUGAR, TIPO_MEDIO_LUGAR = P_TIPO_MEDIO_LUGAR, 
    ESTADO = P_ESTADO WHERE ID_LUGAR = P_ID_LUGAR_REF;
    COMMIT;
END;

COMMIT;